### ISSUE TITLE
Internal error when opening a relation

### ISSUE THREAD

**Issue by momu** [grundid/relation-analyzer#16] opened 2017-11-23 13:23 UTC
I just tried to open the relation http://ra.osmsurround.org/analyzeRelation?relationId=27727
It gave an internal error with the following texts (changed on reload)

    java.lang.NumberFormatException: For input string: "t"

    java.lang.NumberFormatException: For input string: "v48925583"

    java.lang.NumberFormatException: For input string: "v69978049"

    java.lang.NumberFormatException: For input string: "t3"

**Comment by my-na-me** [comment] 2017-12-12 17:12
I notice same issue. The message from Firefox or Chrome (win7 64bit) is like:

Interner Fehler
Fehlermeldung:
java.lang.NumberFormatException: For input string: "t8"
Home

or

Internal error
Message:
java.lang.NumberFormatException: For input string: "v59419625"
Home

By the way, is there workaround to prevent this?

**Comment by grundid** [comment] 2017-12-28 09:24
The issue is fixed now

**Closed by grundid** 2017-12-28 09:24 UTC
